<?php
include_once('script/head.php');
include_once("script/header1.php");
include_once("script/header2.php");
include_once("script/adone.php");
include_once("script/visitorsTitleProcess.php");
include_once("script/visitors.php");
include_once("script/adbottom.php");
include_once('script/footer.php');
?>